# Generated by Django 3.0.2 on 2020-01-16 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(default='', max_length=20, verbose_name='Производитель')),
                ('socket', models.CharField(max_length=20, verbose_name='Сокет')),
                ('freequency', models.IntegerField(default=0, verbose_name='Частота')),
                ('cores', models.IntegerField(default=0, verbose_name='Количество ядер')),
                ('status', models.BooleanField(default=True, verbose_name='Иправность')),
            ],
        ),
        migrations.CreateModel(
            name='HDD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(default='', max_length=20, verbose_name='Производитель')),
                ('hdd_type', models.CharField(max_length=20, verbose_name='Фромфактор')),
                ('capacity', models.IntegerField(default=0, verbose_name='Объём')),
                ('speed', models.IntegerField(default=0, verbose_name='Скорость')),
                ('status', models.BooleanField(default=True, verbose_name='Иправность')),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(default='', max_length=20, verbose_name='Производитель')),
                ('physical_size', models.CharField(max_length=20, verbose_name='Фромфактор')),
                ('amount', models.IntegerField(default=0, verbose_name='Размер')),
                ('ram_type', models.CharField(max_length=20, verbose_name='Тип')),
                ('speed', models.IntegerField(default=0, verbose_name='Скорость')),
                ('status', models.BooleanField(default=True, verbose_name='Иправность')),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(default='', max_length=20, verbose_name='Инвентарный номер')),
                ('manufacturer', models.CharField(default='', max_length=20, verbose_name='Производитель')),
                ('owner', models.CharField(default='', max_length=20, verbose_name='Материально ответственный')),
                ('last_service_date', models.DateTimeField(verbose_name='Дата последней проверки')),
                ('status', models.BooleanField(default=True, verbose_name='Иправность')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uchet.CPU', verbose_name='Процессор')),
                ('hdd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uchet.HDD', verbose_name='Жесткий диск')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uchet.RAM', verbose_name='Оперативная память')),
            ],
        ),
    ]
