# Generated by Django 3.0.2 on 2020-01-14 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket', models.CharField(max_length=20)),
                ('chipset', models.CharField(max_length=20)),
                ('freequency', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HDD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hdd_type', models.CharField(max_length=20)),
                ('capacity', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_size', models.CharField(max_length=20)),
                ('amount', models.IntegerField(default=0)),
                ('ram_type', models.CharField(max_length=20)),
                ('speed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HDD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uchet.HDD')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uchet.CPU')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uchet.RAM')),
            ],
        ),
    ]
