# Generated by Django 3.0.2 on 2020-01-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Исправность'),
        ),
    ]
