# Generated by Django 3.0.2 on 2020-01-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchet', '0002_auto_20200123_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdd',
            name='sdd',
            field=models.BooleanField(default=False, verbose_name='SSD?'),
        ),
    ]
