# Generated by Django 3.0.2 on 2020-01-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchet', '0003_hdd_sdd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='inventory_number',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='sn',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='sn',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='sn',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='Серийный номер'),
        ),
    ]
