# Generated by Django 3.0.2 on 2020-01-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchet', '0004_auto_20200123_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='computer_name',
            field=models.CharField(default='', max_length=20, verbose_name='Имя компьютера'),
        ),
    ]
