# Generated by Django 3.0.2 on 2020-02-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchet', '0006_computer_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(default='', max_length=20, unique=True, verbose_name='Инвентарный номер')),
                ('serial_number', models.CharField(default='', max_length=20, unique=True, verbose_name='Инвентарный номер')),
                ('manufacturer', models.CharField(default='', max_length=20, verbose_name='Производитель')),
                ('owner', models.CharField(default='', max_length=40, verbose_name='Материально ответственный')),
                ('computer_name', models.CharField(blank=True, default='', max_length=20, verbose_name='Имя компьютера')),
                ('last_service_date', models.DateTimeField(verbose_name='Дата последней проверки')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('status', models.BooleanField(default=True, verbose_name='Исправность')),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтера',
            },
        ),
        migrations.AlterField(
            model_name='computer',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='computer_name',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Имя компьютера'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='owner',
            field=models.CharField(default='', max_length=40, verbose_name='Материально ответственный'),
        ),
    ]
