# Generated by Django 3.0.3 on 2020-02-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchet', '0007_auto_20200217_0828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printer',
            options={'verbose_name': 'Принтер', 'verbose_name_plural': 'Принтеры'},
        ),
        migrations.RemoveField(
            model_name='printer',
            name='computer_name',
        ),
        migrations.AlterField(
            model_name='printer',
            name='serial_number',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='Серийный номер'),
        ),
    ]
